// ============================================================
// ELEMENTS — 只有 3 元素
// ============================================================
const ELEM = {
  fire:  { name: '火', color: '#ff6b35', icon: '🔥' },
  water:  { name: '水', color: '#4ecdc4', icon: '💧' },
  earth:  { name: '土', color: '#a68642', icon: '⛰️' },
  wind:  { name: '風', color: '#95e1d3', icon: '🌪️' },
  thunder:  { name: '雷', color: '#ffd700', icon: '⚡' },
  none:  { name: '無', color: '#cccccc', icon: '⬜' },
};
const ELEM_KEYS = ['fire', 'water', 'earth', 'wind', 'thunder', 'none'];

// ============================================================
// BASIC TOWERS — 基礎塔（無元素，Ch1 W1-4 使用）
// ============================================================
const BASIC_TOWERS = {
  arrow: {
    name: '箭塔', icon: '🏹', elem: null,
    levels: [
      { damage: 22, atkSpd: 1.6, range: 3, aoe: 0, cost: 50, skills: [], desc: '單體快攻' },
      { damage: 30, atkSpd: 1.9, range: 3, aoe: 0, cost: 80, skills: [], desc: '攻速提升' },
    ],
  },
  cannon: {
    name: '砲塔', icon: '💣', elem: null,
    levels: [
      { damage: 39, atkSpd: 0.6, range: 3, aoe: 1, cost: 50, skills: [], desc: '範圍慢射' },
      { damage: 54, atkSpd: 0.7, range: 3, aoe: 1, cost: 80, skills: [], desc: '範圍+傷害提升' },
    ],
  },
};
const BASIC_KEYS = ['arrow', 'cannon'];

// ============================================================
// TOWERS — 元素塔（元素 Lv1 起使用，保留作為元素屬性參考）
// ============================================================
const TOWERS = {
  fire: {
    name: '焰舞者', icon: '🔥', elem: 'fire',
    levels: [
      { damage: 35, atkSpd: 1, range: 3, aoe: 0, cost: 50, skills: [], desc: '基礎火塔' },
      { damage: 50, atkSpd: 1.1, range: 3, aoe: 0, cost: 80, skills: [], desc: '攻擊力+攻速提升' },
      null,
      null,
    ],
  },
  water: {
    name: '霜潮使', icon: '💧', elem: 'water',
    levels: [
      { damage: 28, atkSpd: 1, range: 3, aoe: 0, cost: 50, skills: [], desc: '基礎水塔' },
      { damage: 44, atkSpd: 1.1, range: 3, aoe: 0, cost: 80, skills: [], desc: '傷害+攻速提升' },
      null,
      null,
    ],
  },
  earth: {
    name: '岩衛士', icon: '⛰️', elem: 'earth',
    levels: [
      { damage: 30, atkSpd: 0.8, range: 2.5, aoe: 1, cost: 50, skills: [], desc: '基礎土塔(AOE)' },
      { damage: 42, atkSpd: 0.9, range: 2.5, aoe: 1.2, cost: 80, skills: [], desc: '範圍+傷害提升' },
      null,
      null,
    ],
  },
  wind: {
    name: '疾風射手', icon: '🌪️', elem: 'wind',
    levels: [
      { damage: 15, atkSpd: 1.6, range: 4, aoe: 0, cost: 50, skills: [], desc: '基礎風塔(高攻速)' },
      { damage: 20, atkSpd: 1.8, range: 4, aoe: 0, cost: 80, skills: [], desc: '攻速提升' },
      null,
      null,
    ],
  },
  thunder: {
    name: '雷光者', icon: '⚡', elem: 'thunder',
    levels: [
      { damage: 32, atkSpd: 1.1, range: 3.5, aoe: 0, cost: 50, skills: [], desc: '基礎雷塔(遠射)' },
      { damage: 46, atkSpd: 1.2, range: 3.5, aoe: 0, cost: 80, skills: [], desc: '傷害+射程提升' },
      null,
      null,
    ],
  },
  none: {
    name: '虛空行者', icon: '⬜', elem: 'none',
    levels: [
      { damage: 28, atkSpd: 1.2, range: 3, aoe: 0, cost: 50, skills: [], desc: '基礎無屬塔(均衡)' },
      { damage: 40, atkSpd: 1.3, range: 3, aoe: 0, cost: 80, skills: [], desc: '均衡提升' },
      null,
      null,
    ],
  },
};

// ============================================================
// ELEM_BASE — Lv3 元素基底塔（單元素，依箭/砲基底區分）
// Lv2 基礎塔 + 1 元素 pick → 轉為元素塔
// ============================================================
const ELEM_BASE = {
  fire: {
    arrow:  { name: '焰弓手', icon: '🏹🔥', damage: 59, atkSpd: 1.5, range: 3.5, aoe: 0, cost: 130, dmgType: 'fire', desc: '火元素弓手（純 DPS，火屬性加成）',
      skills: [] },
    cannon:  { name: '焰砲台', icon: '💣🔥', damage: 74, atkSpd: 0.9, range: 3, aoe: 1, cost: 130, dmgType: 'fire', desc: '火元素砲台（純 DPS AOE，火屬性加成）',
      skills: [] },
  },
  water: {
    arrow:  { name: '冰弓手', icon: '🏹💧', damage: 59, atkSpd: 1.5, range: 3.5, aoe: 0, cost: 130, dmgType: 'water', desc: '水元素弓手（純 DPS，水屬性加成）',
      skills: [] },
    cannon:  { name: '潮砲台', icon: '💣💧', damage: 74, atkSpd: 0.9, range: 3, aoe: 1, cost: 130, dmgType: 'water', desc: '水元素砲台（純 DPS AOE，水屬性加成）',
      skills: [] },
  },
  earth: {
    arrow:  { name: '岩射手', icon: '🏹⛰️', damage: 59, atkSpd: 1.5, range: 3.5, aoe: 0, cost: 130, dmgType: 'earth', desc: '土元素弓手（純 DPS，土屬性加成）',
      skills: [] },
    cannon:  { name: '岩砲台', icon: '💣⛰️', damage: 74, atkSpd: 0.9, range: 3, aoe: 1, cost: 130, dmgType: 'earth', desc: '土元素砲台（純 DPS AOE，土屬性加成）',
      skills: [] },
  },
  wind: {
    arrow:  { name: '風弓手', icon: '🏹🌪️', damage: 59, atkSpd: 1.5, range: 3.5, aoe: 0, cost: 130, dmgType: 'wind', desc: '風元素弓手（純 DPS，風屬性加成）',
      skills: [] },
    cannon:  { name: '風砲台', icon: '💣🌪️', damage: 74, atkSpd: 0.9, range: 3, aoe: 1, cost: 130, dmgType: 'wind', desc: '風元素砲台（純 DPS AOE，風屬性加成）',
      skills: [] },
  },
  thunder: {
    arrow:  { name: '雷弓手', icon: '🏹⚡', damage: 45, atkSpd: 1.4, range: 3.5, aoe: 0, cost: 130, dmgType: 'thunder', desc: '雷元素弓手（純 DPS，雷屬性加成）',
      skills: [] },
    cannon:  { name: '雷砲台', icon: '💣⚡', damage: 52, atkSpd: 0.8, range: 3, aoe: 1, cost: 130, dmgType: 'thunder', desc: '雷元素砲台（純 DPS AOE，雷屬性加成）',
      skills: [] },
  },
  none: {
    arrow:  { name: '虛空弓', icon: '🏹⬜', damage: 45, atkSpd: 1.4, range: 3.5, aoe: 0, cost: 130, desc: '均衡無技能射手（純數值）',
      skills: [] },
    cannon:  { name: '虛空砲', icon: '💣⬜', damage: 52, atkSpd: 0.8, range: 3, aoe: 1, cost: 130, desc: '均衡無技能範圍砲（純數值 AOE）',
      skills: [] },
  },
};

// ============================================================
// INFUSIONS — Lv4 雙屬塔（6 基底 × 6 注入 = 36 格）
// ============================================================
const INFUSIONS = {
  fire: {
    fire: { name: '暴焰', icon: '🔥🔥',
      lv4: { damage: 110, atkSpd: 1.2, range: 3.5, aoe: 0, cost: 250, score_adj: 1.15, dmgType: 'fire', desc: 'DOT +引燃 攻速慢DPS補正15%',
        skills: [makeSkill('burn',{dot:0.3,dur:3}), makeSkill('ignite',{flat:0.3})] },
    },
    water: { name: '蒸汽塔', icon: '🔥💧',
      lv4: { damage: 77, atkSpd: 1.2, range: 3.5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'fire', desc: '少量DOT+緩速ZONE',
        skills: [makeSkill('burn',{dot:0.3,dur:3}), makeSkill('zone_slow',{radius:1.5,chillStacks:85})] },
    },
    earth: { name: '熔蝕塔', icon: '🔥⛰️',
      lv4: { damage: 48, atkSpd: 1.5, range: 4, aoe: 0, cost: 250, score_adj: 1, dmgType: 'fire', desc: '灼燒+碎甲zone',
        skills: [makeSkill('zone_shred',{radius:1.5,shredStacks:70}), makeSkill('burn',{dot:0.4,dur:3})] },
    },
    wind: { name: '焰息塔', icon: '🔥🌪️',
      lv4: { damage: 55, atkSpd: 1.2, range: 3.5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'fire', desc: '連鎖+越打越快 ',
        skills: [makeSkill('chain',{targets:3,decay:0.7}), makeSkill('ramp',{perHit:0.2,cap:2,switchLoss:5})] },
    },
    thunder: { name: '電漿塔', icon: '🔥⚡',
      lv4: { damage: 90, atkSpd: 1.2, range: 3.5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'fire', desc: '灼燒時額外真傷',
        skills: [makeSkill('burn',{dot:0.3,dur:3}), makeSkill('execute',{threshold:0.5,mult:1.5})] },
    },
    none: { name: '混沌焰', icon: '🔥⬜',
      lv4: { damage: 95, atkSpd: 1.1, range: 3, aoe: 0, cost: 250, score_adj: 1, dmgType: 'fire', desc: '隨機傷害+暴擊灼燒',
        skills: [makeSkill('burn',{dot:0.25,dur:3}), makeSkill('unstable',{variance:0.4})] },
    },
  },
  water: {
    fire: { name: '蒸汽塔', icon: '💧🔥',
      lv4: { damage: 40, atkSpd: 1.2, range: 3.5, aoe: 1, cost: 250, score_adj: 0.82, dmgType: 'water', desc: 'AOE灼燒區域',
        skills: [makeSkill('zone_slow',{radius:1.5,chillStacks:50}), makeSkill('chill',{stacksPerHit:11})] },
    },
    water: { name: '深寒', icon: '💧💧',
      lv4: { damage: 64, atkSpd: 1.4, range: 3.5, aoe: 1, cost: 250, score_adj: 1, dmgType: 'water', desc: '冰冷 技能分難算 視為DPS範圍塔 DPS補正50%',
        skills: [makeSkill('chill',{stacksPerHit:10})] },
    },
    earth: { name: '泥沼塔', icon: '💧⛰️',
      lv4: { damage: 50, atkSpd: 1.3, range: 4, aoe: 0, cost: 250, score_adj: 1, dmgType: 'water', desc: '冰冷+碎甲',
        skills: [makeSkill('chill',{stacksPerHit:15}), makeSkill('shred',{stacksPerHit:6})] },
    },
    wind: { name: '暴雨塔', icon: '💧🌪️',
      lv4: { damage: 45, atkSpd: 1.7, range: 3.5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'water', desc: '寒氣擴散光環',
        skills: [makeSkill('chill',{stacksPerHit:12}), makeSkill('ramp',{perHit:0.2,cap:2,switchLoss:5})] },
    },
    thunder: { name: '感電塔', icon: '💧⚡',
      lv4: { damage: 58, atkSpd: 1.2, range: 3.5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'water', desc: '寒氣目標連鎖彈射',
        skills: [makeSkill('chill',{stacksPerHit:1}), makeSkill('chain',{targets:2,decay:0.5})] },
    },
    none: { name: '虛空泉', icon: '💧⬜',
      lv4: { damage: 55, atkSpd: 1, range: 3, aoe: 1, cost: 250, score_adj: 1, dmgType: 'water', desc: '定身+爆傷',
        skills: [makeSkill('chill',{stacksPerHit:1}), makeSkill('warp',{dur:0.8,cd:6})] },
    },
  },
  earth: {
    fire: { name: '熔蝕塔', icon: '⛰️🔥',
      lv4: { damage: 80, atkSpd: 1.1, range: 5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'earth', desc: '碎甲+灼燒',
        skills: [makeSkill('burn',{dot:0.25,dur:3}), makeSkill('pierce',{dmgDown:0.15,count:5})] },
    },
    water: { name: '泥沼塔', icon: '⛰️💧',
      lv4: { damage: 55, atkSpd: 1, range: 5, aoe: 1, cost: 250, score_adj: 1, dmgType: 'earth', desc: '碎甲+減速區域',
        skills: [makeSkill('zone_slow',{radius:1.5,chillStacks:50}), makeSkill('zone_shred',{radius:1.5,shredStacks:50})] },
    },
    earth: { name: '磐石', icon: '⛰️⛰️',
      lv4: { damage: 160, atkSpd: 0.8, range: 5, aoe: 0, cost: 250, score_adj: 1.21, dmgType: 'earth', desc: '低速 超高傷 穿透 低速DPS補正',
        skills: [makeSkill('pierce',{dmgDown:0.15,count:5})] },
    },
    wind: { name: '沙暴塔', icon: '⛰️🌪️',
      lv4: { damage: 65, atkSpd: 1.5, range: 3.5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'earth', desc: '範圍碎甲',
        skills: [makeSkill('shred',{stacksPerHit:7}), makeSkill('ramp',{perHit:0.2,cap:0.2,switchLoss:5})] },
    },
    thunder: { name: '震盪塔', icon: '⛰️⚡',
      lv4: { damage: 72, atkSpd: 0.8, range: 3, aoe: 1, cost: 250, score_adj: 1, dmgType: 'earth', desc: '地震波定身',
        skills: [makeSkill('shred',{stacksPerHit:3}), makeSkill('warp',{dur:0.6,cd:8})] },
    },
    none: { name: '重力塔', icon: '⛰️⬜',
      lv4: { damage: 48, atkSpd: 0.9, range: 3, aoe: 1.5, cost: 250, score_adj: 1, dmgType: 'earth', desc: '區域強減速',
        skills: [makeSkill('shred',{stacksPerHit:3}), makeSkill('chill',{stacksPerHit:2})] },
    },
  },
  wind: {
    fire: { name: '焰息塔', icon: '🌪️🔥',
      lv4: { damage: 54, atkSpd: 1.4, range: 4, aoe: 0, cost: 250, score_adj: 1, dmgType: 'wind', desc: '快灼燒+傷害光環',
        skills: [makeSkill('burn',{dot:0.25,dur:3}), makeSkill('ramp',{perHit:0.2,cap:2,switchLoss:5})] },
    },
    water: { name: '暴雨塔', icon: '🌪️💧',
      lv4: { damage: 46, atkSpd: 1.4, range: 4, aoe: 0, cost: 250, score_adj: 1, dmgType: 'wind', desc: '高頻冰冷+射程光環',
        skills: [makeSkill('ramp',{perHit:0.2,cap:2,switchLoss:5}), makeSkill('execute',{threshold:0.2,mult:2})] },
    },
    earth: { name: '沙暴塔', icon: '🌪️⛰️',
      lv4: { damage: 40, atkSpd: 1.4, range: 4.5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'wind', desc: '高頻碎甲',
        skills: [makeSkill('ramp',{perHit:0.15,cap:1.5,switchLoss:3}), makeSkill('pierce',{dmgDown:0.35,count:2})] },
    },
    wind: { name: '疾風', icon: '🌪️🌪️',
      lv4: { damage: 45, atkSpd: 1.5, range: 4, aoe: 0, cost: 250, score_adj: 1, dmgType: 'wind', desc: '射程光環+ramp增強',
        skills: [makeSkill('ramp',{perHit:0.3,cap:3,switchLoss:5})] },
    },
    thunder: { name: '雷暴塔', icon: '🌪️⚡',
      lv4: { damage: 38, atkSpd: 2, range: 4.5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'wind', desc: '高頻落雷',
        skills: [makeSkill('ramp',{perHit:0.05,cap:0.3,switchLoss:3}), makeSkill('chain',{targets:2,decay:0.6})] },
    },
    none: { name: '相位塔', icon: '🌪️⬜',
      lv4: { damage: 30, atkSpd: 2.2, range: 5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'wind', desc: '穿甲光環',
        skills: [makeSkill('ramp',{perHit:0.05,cap:0.3,switchLoss:3}), makeSkill('pierce',{dmgDown:0.15,count:3})] },
    },
  },
  thunder: {
    fire: { name: '電漿塔', icon: '⚡🔥',
      lv4: { damage: 80, atkSpd: 1.1, range: 3.5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'thunder', desc: '%HP+灼燒',
        skills: [makeSkill('hpPct',{pct:0.03,every:3,cd:1}), makeSkill('burn',{dot:0.2,dur:3})] },
    },
    water: { name: '感電塔', icon: '⚡💧',
      lv4: { damage: 65, atkSpd: 1.1, range: 3.5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'thunder', desc: '%HP+連鎖+冰冷',
        skills: [makeSkill('hpPct',{pct:0.02,every:3,cd:1}), makeSkill('chain',{targets:2,decay:0.5}), makeSkill('chill',{stacksPerHit:1})] },
    },
    earth: { name: '震盪塔', icon: '⚡⛰️',
      lv4: { damage: 70, atkSpd: 1, range: 3, aoe: 1, cost: 250, score_adj: 1, dmgType: 'thunder', desc: '%HP+碎甲',
        skills: [makeSkill('hpPct',{pct:0.02,every:3,cd:1}), makeSkill('shred',{stacksPerHit:3})] },
    },
    wind: { name: '雷暴塔', icon: '⚡🌪️',
      lv4: { damage: 55, atkSpd: 1.5, range: 4, aoe: 0, cost: 250, score_adj: 1, dmgType: 'thunder', desc: '%HP+高頻連鎖',
        skills: [makeSkill('hpPct',{pct:0.02,every:4,cd:1}), makeSkill('chain',{targets:3,decay:0.5})] },
    },
    thunder: { name: '雷霆', icon: '⚡⚡',
      lv4: { damage: 60, atkSpd: 2.2, range: 3.5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'thunder', desc: '強%HP+斬殺+賞金',
        skills: [makeSkill('multishot',{every:3,shots:3,killBonus:0.5,killDur:3})] },
    },
    none: { name: '賞金塔', icon: '⚡⬜',
      lv4: { damage: 60, atkSpd: 1.1, range: 3.5, aoe: 0, cost: 250, score_adj: 1.4, dmgType: 'thunder', desc: '金幣標記',
        skills: [makeSkill('hpPct',{pct:0.02,every:4,cd:1}), makeSkill('killGold',{bonus:5})] },
    },
  },
  none: {
    fire: { name: '混沌焰', icon: '⬜🔥',
      lv4: { damage: 80, atkSpd: 1.1, range: 3, aoe: 0, cost: 250, score_adj: 1.1, dmgType: 'none', desc: '隨機傷害+灼燒',
        skills: [makeSkill('unstable',{variance:0.4}), makeSkill('burn',{dot:0.2,dur:3})] },
    },
    water: { name: '虛空泉', icon: '⬜💧',
      lv4: { damage: 55, atkSpd: 1, range: 3, aoe: 1, cost: 250, score_adj: 1, dmgType: 'none', desc: '定身+冰冷',
        skills: [makeSkill('warp',{dur:0.8,cd:6}), makeSkill('chill',{stacksPerHit:1})] },
    },
    earth: { name: '重力塔', icon: '⬜⛰️',
      lv4: { damage: 48, atkSpd: 0.9, range: 3, aoe: 1.5, cost: 250, score_adj: 1, dmgType: 'none', desc: '區域強減速+碎甲',
        skills: [makeSkill('chill',{stacksPerHit:2}), makeSkill('shred',{stacksPerHit:2})] },
    },
    wind: { name: '相位塔', icon: '⬜🌪️',
      lv4: { damage: 35, atkSpd: 1.8, range: 4.5, aoe: 0, cost: 250, score_adj: 1, dmgType: 'none', desc: '穿甲光環',
        skills: [makeSkill('pierce',{dmgDown:0.15,count:3}), makeSkill('aura_dmg',{radius:2,flat:5,pct:0})] },
    },
    thunder: { name: '賞金塔', icon: '⬜⚡',
      lv4: { damage: 55, atkSpd: 1.1, range: 3.5, aoe: 0, cost: 250, score_adj: 1.5, dmgType: 'none', desc: '金幣標記+%HP',
        skills: [makeSkill('killGold',{bonus:5}), makeSkill('hpPct',{pct:0.02,every:4,cd:1})] },
    },
    none: { name: '虛空', icon: '⬜⬜',
      lv4: { damage: 105, atkSpd: 1.7, range: 4, aoe: 0, cost: 250, score_adj: 1.46, dmgType: 'none', desc: '無屬注入：無弱點穩定輸出 + 基礎擊殺獎金',
        skills: [makeSkill('killGold',{bonus:0.25})] },
    },
  },
};

// ============================================================
// TRIPLE_TOWERS — Lv5 三屬塔
// ============================================================
const TRIPLE_TOWERS = {
  'earth_fire_water': { name: '溫泉塔', icon: '♨️',
    lv5: { damage: 88, atkSpd: 1.2, range: 3.5, aoe: 1, cost: 400, dmgType: 'fire', desc: '小幅攻速光環+灼燒',
      skills: [makeSkill('burn',{dot:0.25,dur:3}), makeSkill('aura_atkSpd',{radius:2,bonus:0.15}), makeSkill('shred',{stacksPerHit:5})] },
  },
  'fire_water_wind': { name: '颶風塔', icon: '🌀',
    lv5: { damage: 70, atkSpd: 1.6, range: 4, aoe: 1, cost: 400, dmgType: 'wind', desc: '移動式灼燒風暴',
      skills: [makeSkill('aura_range',{radius:2,bonus:1}), makeSkill('killGold',{bonus:0.15})] },
  },
  'fire_thunder_water': { name: '間歇塔', icon: '🌋',
    lv5: { damage: 100, atkSpd: 1, range: 3.5, aoe: 1.5, cost: 400, dmgType: 'fire', desc: '大範圍爆發+灼燒+寒氣',
      skills: [makeSkill('burn',{dot:0.3,dur:3}), makeSkill('chill',{stacksPerHit:1}), makeSkill('hpPct',{pct:0.02,every:3,cd:1})] },
  },
  'earth_fire_wind': { name: '熔爐塔', icon: '🏭',
    lv5: { damage: 86, atkSpd: 1.4, range: 3.5, aoe: 0.8, cost: 400, dmgType: 'earth', desc: '永久傷害加成',
      skills: [makeSkill('permaBuff',{atkPerKill:2}), makeSkill('ramp',{perHit:0.15,cap:1.5,switchLoss:5})] },
  },
  'earth_fire_thunder': { name: '火山塔', icon: '🌋',
    lv5: { damage: 110, atkSpd: 0.8, range: 3, aoe: 1.5, cost: 400, dmgType: 'earth', desc: '噴發+碎甲+岩漿區',
      skills: [makeSkill('burn',{dot:0.35,dur:3}), makeSkill('shred',{stacksPerHit:4}), makeSkill('zone_slow',{radius:1.5,chillStacks:40})] },
  },
  'fire_thunder_wind': { name: '雷焰塔', icon: '⚡🔥',
    lv5: { damage: 75, atkSpd: 1.6, range: 4, aoe: 0, cost: 400, dmgType: 'fire', desc: '易傷烙印 +25%',
      skills: [makeSkill('burn',{dot:0.2,dur:3}), makeSkill('vulnerability',{stacksPerHit:4}), makeSkill('chain',{targets:2,decay:0.5})] },
  },
  'earth_water_wind': { name: '沼澤塔', icon: '🌿',
    lv5: { damage: 65, atkSpd: 1.4, range: 4, aoe: 1, cost: 400, dmgType: 'earth', desc: '大範圍減速+碎甲區',
      skills: [makeSkill('zone_slow',{radius:1.5,chillStacks:50}), makeSkill('aura_dmg',{radius:2,flat:0,pct:0.15}), makeSkill('zone_shred',{radius:1.5,shredStacks:50})] },
  },
  'earth_thunder_water': { name: '腐蝕塔', icon: '☠️',
    lv5: { damage: 85, atkSpd: 1, range: 3, aoe: 1.2, cost: 400, dmgType: 'earth', desc: '%HP+碎甲+易傷',
      skills: [makeSkill('hpPct',{pct:0.03,every:3,cd:1}), makeSkill('shred',{stacksPerHit:3}), makeSkill('vulnerability',{stacksPerHit:3})] },
  },
  'thunder_water_wind': { name: '暴風塔', icon: '⛈️',
    lv5: { damage: 65, atkSpd: 1.5, range: 4.5, aoe: 1, cost: 400, dmgType: 'thunder', desc: '週期閃電微定身',
      skills: [makeSkill('chill',{stacksPerHit:1}), makeSkill('chain',{targets:3,decay:0.4}), makeSkill('warp',{dur:0.3,cd:5})] },
  },
  'earth_thunder_wind': { name: '磁力塔', icon: '🧲',
    lv5: { damage: 90, atkSpd: 1, range: 3, aoe: 1.2, cost: 400, dmgType: 'earth', desc: '蓄能爆發+定身',
      skills: [makeSkill('shred',{stacksPerHit:3}), makeSkill('hpPct',{pct:0.03,every:3,cd:1}), makeSkill('warp',{dur:0.5,cd:6})] },
  },
  'fire_none_thunder': { name: '逆風塔', icon: '🌬️',
    lv5: { damage: 80, atkSpd: 1.2, range: 3.5, aoe: 0, cost: 400, dmgType: 'fire', desc: '擊退（反克制風）',
      skills: [makeSkill('knockback',{dist:2,cd:6}), makeSkill('burn',{dot:0.2,dur:3}), makeSkill('hpPct',{pct:0.02,every:4,cd:1})] },
  },
  'fire_none_water': { name: '逆雷塔', icon: '🔌',
    lv5: { damage: 75, atkSpd: 1.1, range: 3.5, aoe: 1, cost: 400, dmgType: 'fire', desc: '迷你靜電+減速（反克制雷）',
      skills: [makeSkill('chain',{targets:2,decay:0.5}), makeSkill('chill',{stacksPerHit:1}), makeSkill('burn',{dot:0.15,dur:3})] },
  },
  'earth_none_water': { name: '逆焰塔', icon: '🧊',
    lv5: { damage: 70, atkSpd: 1, range: 3, aoe: 1.2, cost: 400, dmgType: 'earth', desc: '灼燒+碎甲（反克制火）',
      skills: [makeSkill('burn',{dot:0.25,dur:3}), makeSkill('shred',{stacksPerHit:3}), makeSkill('chill',{stacksPerHit:1})] },
  },
  'earth_none_wind': { name: '逆潮塔', icon: '🏜️',
    lv5: { damage: 60, atkSpd: 1.3, range: 3.5, aoe: 1.2, cost: 400, dmgType: 'earth', desc: '寒氣+碎甲（反克制水）',
      skills: [makeSkill('chill',{stacksPerHit:2}), makeSkill('shred',{stacksPerHit:3}), makeSkill('ramp',{perHit:0.04,cap:0.2,switchLoss:3})] },
  },
  'none_thunder_wind': { name: '逆岩塔', icon: '💨',
    lv5: { damage: 55, atkSpd: 1.6, range: 4.5, aoe: 0, cost: 400, dmgType: 'none', desc: '碎甲+%HP（反克制土）',
      skills: [makeSkill('shred',{stacksPerHit:3}), makeSkill('hpPct',{pct:0.02,every:4,cd:1}), makeSkill('ramp',{perHit:0.05,cap:0.3,switchLoss:3})] },
  },
  'earth_fire_none': { name: '隕石塔', icon: '☄️',
    lv5: { damage: 130, atkSpd: 0.5, range: 3, aoe: 2, cost: 400, dmgType: 'earth', desc: '隨機位置超高傷',
      skills: [makeSkill('burn',{dot:0.3,dur:3}), makeSkill('shred',{stacksPerHit:4}), makeSkill('unstable',{variance:0.5})] },
  },
  'fire_none_wind': { name: '燎原塔', icon: '🔥🌪️',
    lv5: { damage: 50, atkSpd: 2.5, range: 5, aoe: 0, cost: 400, dmgType: 'fire', desc: '快速收割+範圍灼燒',
      skills: [makeSkill('burn',{dot:0.15,dur:3}), makeSkill('ramp',{perHit:0.06,cap:0.4,switchLoss:3}), makeSkill('pierce',{dmgDown:0.1,count:4})] },
  },
  'none_water_wind': { name: '迷霧塔', icon: '🌫️',
    lv5: { damage: 45, atkSpd: 1.5, range: 4, aoe: 1.5, cost: 400, dmgType: 'none', desc: '速度隨機波動區域',
      skills: [makeSkill('chill',{stacksPerHit:2}), makeSkill('zone_slow',{radius:1.5,chillStacks:40}), makeSkill('ramp',{perHit:0.04,cap:0.25,switchLoss:3})] },
  },
  'none_thunder_water': { name: '吞噬塔', icon: '🕳️',
    lv5: { damage: 70, atkSpd: 1.1, range: 3.5, aoe: 0, cost: 400, dmgType: 'none', desc: '吸血轉金幣',
      skills: [makeSkill('lifedrain',{pct:0.03}), makeSkill('hpPct',{pct:0.02,every:3,cd:1}), makeSkill('killGold',{bonus:3})] },
  },
  'earth_none_thunder': { name: '混沌塔', icon: '🎲',
    lv5: { damage: 75, atkSpd: 1, range: 3, aoe: 1, cost: 400, dmgType: 'earth', desc: '碎甲+%HP+隨機',
      skills: [makeSkill('shred',{stacksPerHit:3}), makeSkill('hpPct',{pct:0.02,every:4,cd:1}), makeSkill('unstable',{variance:0.3})] },
  },
};

// ============================================================
// PURE_TOWERS — Lv5 純屬強化 / Lv6 純屬終極（同元素×3 + 精華）
// ============================================================
const PURE_TOWERS = {
  fire: { name: '業炎塔', icon: '🔥🔥🔥',
    lv5: { damage: 135, atkSpd: 1.2, range: 4, aoe: 0, cost: 350, dmgType: 'fire', desc: '純火強化：灼燒強化（含引燃），穩定 DOT 輸出',
      skills: [makeSkill('burn',{dot:0.45,dur:3}), makeSkill('ignite',{flat:0.35})] },
    lv6: { damage: 170, atkSpd: 1.2, range: 4.5, aoe: 0, cost: 600, dmgType: 'fire', desc: '純火終極：灼燒+引燃+引爆（燃爆達 3 層真傷，無視護甲）',
      skills: [makeSkill('burn',{dot:0.5,dur:4}), makeSkill('ignite',{flat:0.4}), makeSkill('detonate',{ratio:1,radius:1.5})] },
  },
  water: { name: '冰河塔', icon: '💧💧💧',
    lv5: { damage: 75, atkSpd: 1.5, range: 4, aoe: 1, cost: 350, dmgType: 'water', desc: '純水強化：AOE 冰冷（疊加中），緩速延長敵人在射程內的時間',
      skills: [makeSkill('chill',{stacksPerHit:12}), makeSkill('hpPct',{pct:0.04,every:2,cd:0})] },
    lv6: { damage: 85, atkSpd: 1.2, range: 4.5, aoe: 1.6, cost: 600, dmgType: 'water', desc: '純水終極：AOE 冰冷（疊加中）+ %HP 侵蝕真傷（每 2 攻擊）',
      skills: [makeSkill('chill',{stacksPerHit:10}), makeSkill('hpPct',{pct:0.04,every:2,cd:0}), makeSkill('freeze',{dur:1,threshold:30})] },
  },
  earth: { name: '磐石塔', icon: '⛰️⛰️⛰️',
    lv5: { damage: 215, atkSpd: 0.8, range: 5, aoe: 0, cost: 350, dmgType: 'earth', desc: '純土強化：穿透貫穿（後排−dmgDown傷害），大射程重型砲擊',
      skills: [makeSkill('pierce',{dmgDown:0.15,count:5})] },
    lv6: { damage: 180, atkSpd: 0.8, range: 5, aoe: 0, cost: 600, dmgType: 'earth', desc: '純土終極：穿透貫穿（強化）+ 傷害光環（全場 +20% 傷害）',
      skills: [makeSkill('pierce',{dmgDown:0.25,count:5}), makeSkill('aura_dmg',{radius:2.5,flat:0,pct:0.2})] },
  },
  wind: { name: '颶風塔', icon: '🌪️🌪️🌪️',
    lv5: { damage: 70, atkSpd: 1.7, range: 4.5, aoe: 0, cost: 350, dmgType: 'wind', desc: '純風強化：越攻越快（切換目標扣層，不歸零），中等單體持續輸出',
      skills: [makeSkill('ramp',{perHit:0.3,cap:3,switchLoss:5})] },
    lv6: { damage: 90, atkSpd: 1.8, range: 4.5, aoe: 0, cost: 600, dmgType: 'wind', desc: '純風終極：越攻越快（強化）+ 射程光環（全場 +1 射程）',
      skills: [makeSkill('ramp',{perHit:0.06,cap:0.8,switchLoss:3}), makeSkill('aura_range',{radius:2.5,bonus:1})] },
  },
  thunder: { name: '雷神塔', icon: '⚡⚡⚡',
    lv5: { damage: 100, atkSpd: 1.5, range: 3.5, aoe: 0, cost: 350, dmgType: 'thunder', desc: '純雷強化：三連射（每 3 攻觸發），快速多目標爆發',
      skills: [makeSkill('multishot',{every:3,shots:3,killBonus:0.3,killDur:2})] },
    lv6: { damage: 120, atkSpd: 1.6, range: 4, aoe: 0, cost: 600, dmgType: 'thunder', desc: '純雷終極：三連射（每 2 攻觸發）+ 射速光環（全場 +25% 攻速）',
      skills: [makeSkill('multishot',{every:2,shots:3,killBonus:0.5,killDur:3}), makeSkill('aura_atkSpd',{radius:2.5,bonus:0.25})] },
  },
  none: { name: '混沌核', icon: '⬜⬜⬜',
    lv5: { damage: 70, atkSpd: 1.4, range: 4, aoe: 0, cost: 350, dmgType: 'none', desc: '純無強化：擊殺獎金 + 財富積累（持有金幣轉化傷害）',
      skills: [makeSkill('killGold',{bonus:0.5}), makeSkill('wealthScale',{divisor:25,cap:30})] },
    lv6: { damage: 80, atkSpd: 1.4, range: 4, aoe: 0, cost: 600, dmgType: 'none', desc: '純無終極：擊殺獎金 + 財富積累（強化）+ 利息（每波依持有金幣直接加金）',
      skills: [makeSkill('killGold',{bonus:1}), makeSkill('wealthScale',{divisor:20,cap:50}), makeSkill('interest',{rate:0.05,cap:40})] },
  },
};
